language: python
python:
- 3.9
- 3.8
- 3.7
install: pip install -U tox-travis
script: tox
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: teanijarv
  password:
    secure: zwLzfQC/ImuhxTChsrKBNQ922KrSG3fSwkz2D/cmyuIdS1MWo4DrNMujF0x7vrpMFRCiudlSmce2RKgLqK9ItzId7oKYIDFB6vFZC/Hwc9MGIt8fLE8f6MxVWrgyLyCH2kb3U2lcOGXv/jo5XvbVx1Bsa8JMHl3DidjQQP1Gcd/IQAjZKPauhaBRzaVN8qpbpFzAcl1mavNhdJxawWADazUde5AyoMetXgX3pAImaagEhhwEJKNXlb3fj0jDI8W6E/FRycKUuWM/biafafxcBPCxPFifpQp1XCz7sXg/Urpu8GU+GpLkigvjloe22JSEXBBglsR/Yf6pnCm9FskdVs2R/pylAe7081T6Kz8FexqIyR/UfCOHVdmV3h8f/L5CSm2EaX6Nl2hbZc1j2sPWNlqt2+KKNobOtGbTd0vzOWxc4uz/sV/+9UsevMX7iPQLSws67Ektl0dlTVhHVl61FXtZI3Z2DQaODdN1jHhcnD27QyjgW+xdMjazKzQyWhgi5ANwcBRoZL8ixu7RLWesR5Qt8co5roH1Iwx9yg5CwKs/OMuINWXBnZdveh6W7hBCjT0zR4fUx9iqf2758iTkd/iP7zCjhY/AB832UF2emS01WU76uP+wTBSw8ICp5VJWN4ppTaGwgPurgZd3EaaDRxS/VYm3lUwXQsA3Eaa+MSQ=
  on:
    tags: true
    repo: teanijarv/HLR
    python: 3.9
